### ISSUE TITLE
Failed links on subpath installs

### ISSUE THREAD

**Issue by Jaxom99** [kijimaD/dokuwiki_theme_2#1]
On my install on a subdomain and a subpath (test.example.com/wiki), the Return button leads to a 404 error, because it points to test.example.com  and doesn't take the path into account.

**Comment by Jaxom99** [comment]
So, is it fixed ? Yes, I can see a new PR. 
Thanks you very much :pray: :wink:

**Comment by kijimad** [comment]
Thank you, too!
