### ISSUE TITLE
Images not working as in the default theme.

### ISSUE THREAD

**Issue by u0nel** [kijimaD/dokuwiki_theme_2#2]
I noticed 2 things:
1. You can't put several images next to each other
2. If you have a small picture, you can't put it next to the text, it's always under the text.

I hope that can be fixed, and if this change is there an purpose, I hope there will be an option to disable that.

**Comment by kijimad** [comment]
Thank you for your issue!
Maybe I can fix it. Please reinstall and test it!

**Comment by u0nel** [comment]
You fixed it already? I reinstalled it, but the it's still Luke that.

**Comment by kijimad** [comment]
Sorry,  I did not reflect on the download.. It's OK this time, please retry it!

**Comment by u0nel** [comment]
Thanks. It works now.
